fix: Use PACKAGE_PREFIX_DIR to ensure relocatable CMake install for conan
ignitionrobotics/ign-cmake pull request #129
Opened 2020-11-17 12:29 UTC by Pro

Using CMAKE_INSTALL_PREFIX causes build issues when you relocate the installed CMake package, i.e., as it is done in conan.

CMAKE_INSTALL_PREFIX should not be used in the cmake.in files directly. The `@PACKAGE_INIT@` macro initializes `PACKAGE_PREFIX_DIR` correspondingly.

See also:
https://github.com/osrf/gazebo/issues/2782

cc @stefanbuettner

2020-11-23 22:03 UTC, scpeters requested changes

2020-11-23 22:03 UTC, scpeters commented on cmake/pkgconfig/ignition.pc.in
> +prefix=${pcfiledir}/../..
as discussed in dartsim/dart#1527 (comment), this relative path is incorrect on Ubuntu

2021-01-08 23:48 UTC, scpeters commented on cmake/pkgconfig/ignition.pc.in
> +prefix=${pcfiledir}/../..
I've updated the `.pc.in` templates for downstream ignition packages in 1e39fa0 and the `.pc` file for ign-cmake2 itself in b95d20f

2021-01-08 23:49 UTC, scpeters commented
I think it's good now with my fixes, based on the approach in https://github.com/dartsim/dart/pull/1529 and https://github.com/osrf/sdformat/pull/419, but I'd like another set of eyes and some testing if possible

cc @j-rivero @caguero

2021-01-20 00:53 UTC, scpeters approved these changes

2021-02-04 17:21 UTC, scpeters commented
perhaps we can test this by including it in a prerelease (see #147)

2021-02-04 17:31 UTC, scpeters commented
I'm going to merge this now and include in a prerelease to get further testing

2021-02-04 17:32 UTC, merged

2021-02-04 17:37 UTC, j-rivero commented
> I'm going to merge this now and include in a prerelease to get further testing

You were a bit faster merging than I commenting: I tried this today, seems to work fine for all the scenarios I tried: colcon workspace to build ign-math7, simulate a release in Debian packaging system (using `-DCMAKE_INSTALL_LIBDIR=lib/aarch64-linux-gnu`, would be great to set a test for this) or just manually inspecting the file with the default no-arguments. I see no reason not to merge this one. Nice work.

2021-02-04 17:49 UTC, scpeters commented
> > I'm going to merge this now and include in a prerelease to get further testing
> 
> You were a bit faster merging than I was commenting: I tried this today, seems to work fine for all the scenarios I tried: colcon workspace to build ign-math7, simulate a release in Debian packaging system (using `-DCMAKE_INSTALL_LIBDIR=lib/aarch64-linux-gnu`, would be great to set a test for this) or just manually inspecting the file with the default no-arguments. I see no reason not to merge this one. Nice work.

sorry for not waiting! we can see how the prerelease goes